version: '3.4'

services:
  imagerepository:
    image: imagerepository
    restart: always
    build: .
    ports:
      - 8080:8080
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    links:
      - mongodb
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - 27017:27017
    volumes: 
      - data:/data/db

volumes:
  data:
